services:
  wallet-app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./.env:/app/.env
      - ./config:/app/config:ro
      - ./logs:/app/logs
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
        wallet-db:
          condition: service_healthy
    restart: unless-stopped

  wallet-db:
    image: postgres:16
    env_file: .env
    volumes:
      - wallet-db-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  wallet-db-data:
